GPU: ['0']
NETWORK:
  TRANSFORM_DIM: 4
  TEMPORAL_LENGTH: 1
  DIM_JOINT: 8
  USE_GT_TRANSFORM: False
  NUM_CHANNELS: 512
  AFTER_MHF_DIM: 1024
  T_FORMER:
    NUM_CHANNELS: 512
    NUM_LAYERS: 4
  TYPE: 'MHT'
  ROT_MODEL:
    NUM_LAYERS: 1
    NUM_CHANNELS: 256
  M_FORMER:
    GT_TRANSFORM_RES: False
TEST:
  NUM_FRAMES: [1]
  NUM_VIEWS: [4]
TRAIN:
  INTER_LOSS_WEIGHT: [0.1, 0.4]
  CONSIS_LOSS_WEIGHT: 0.01
  RESUME_CHECKPOINT: '/home/facebooksurrounduser/Documents/RLBench_works/pose_obj_3d_from_image/checkpoint/submit/config_full_pose_groc_2023-02-26-16-53/model.bin'
  RESUME: True
OBJ_POSE_DATA:
  PROJ_Frm_3DCAM: False
  NUM_OBJS: 5
  DIM_OBJ: 16
  NUM_WPS: 5
  DIM_WP: 8
  IMAGES_PATH: '/media/facebooksurrounduser/data/RLBench_data/multi_view_2D_3D_keypoints_300ex_paper_groceries/test/'
  SUBJECTS_TRAIN: ['T3']
  SUBJECTS_TEST: ['T3']
  